#!/bin/sh

# This makes some assumptions about:
# - Which branches you want to keep (egrep -v line)
# - That it's safe to delete branches from the "origin" remote

BRANCH=development

git branch --remote --merged origin/$BRANCH | \
  egrep -v "(development|preview|master|beta)" | \
  grep "origin/" | \
  sed 's/origin\///g' | \
  xargs -n1 git push origin --delete

