#!/bin/sh

# This makes some assumptions about:
# - Which branches you want to keep (egrep -v line)

BRANCH=beta

git branch --merged $BRANCH | \
  egrep -v "(development|preview|master)" | \
  xargs -n 1 git branch -d
